#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 17 11:40:09 2021

@author: clemens
"""
#######################################################
import pandas as pd
import numpy as np
from faker import Faker
import seaborn as sns
import matplotlib.pyplot as plt

plt.rcParams['figure.dpi']= 300

#######################################################
#import mplleaflet # creates interactive maps using openStreetMap

# generating Fake Data on an individual level
fake = Faker("de_DE")
Faker.seed(0)

num_rows = 10000

# populate df using fake data profiles
df = []
for _ in range(num_rows):
    df.append(
        fake.profile()
    )

df = pd.DataFrame(df)

# adding some financal fake data
df["income"] = np.random.randint(1200, 5550, size = [1, num_rows]).flat
df["assets"] = df["income"] * np.random.sample(num_rows)*5

# generating some more differences in the data
df.loc[df["sex"] == "F", "income"] = df["income"] * np.random.sample(num_rows)
df.rename(columns = { "Income":"income", "Assets" : "assets"}, inplace=True)
df['birthdate'] = pd.to_datetime(df['birthdate'])

# some simple visualizations
sns.boxenplot(x="income", y = "sex",data=df)
sns.violinplot(y="income", x = "sex",data=df, cut = 0, orient="v")

# dots with boxenplots
p = sns.stripplot("income", y = "sex", hue = "blood_group",data = df.iloc[:1000,:], jitter = 0.25)
sns.boxenplot(x="income", y = "sex",data=df)
plt.legend(loc = 1)

